"""
DocForge AI — backend/services/section_generator.py
════════════════════════════════════════════════════════════════
Section-by-Section Document Generation Engine

Based on notebook architecture:
  User Input → Dept/DocType/Session
  → LLM generates questions per section
  → User answers
  → Each section generated by SEPARATE LLM call (streaming)
  → Sections combined into final document
  → Pushed to Notion

Key design decisions from notes:
  - "More than 1 prompt" → one prompt per section
  - "Combine API + Stream + Prompt" → AsyncGenerator + streaming
  - "Section-by-section generation" → independent, accurate, better formatting
  - "Dynamic Prompt → LLM questions → Ans" → each section has its own context
"""

from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from backend.core.config import settings
from backend.core.logger import logger
from prompts.templates import get_sections_for_doc_type, build_answers_block
from typing import AsyncGenerator
import asyncio


# ─────────────────────────────────────────────────────────────────────────────
#  AUTO-GENERATED HEADER (always first — no user input needed)
#  Metadata 100% · Version Control 98% · Confidentiality 96%
# ─────────────────────────────────────────────────────────────────────────────
HEADER_PROMPT = PromptTemplate(
    input_variables=["industry", "department", "document_type", "author", "doc_ref"],
    template="""You are an enterprise documentation specialist.

Generate ONLY the administrative governance header for this document.
Include exactly these three blocks in order:

1. DOCUMENT METADATA TABLE
   Fields: Title | Reference ID ({doc_ref}) | Department | Author | Status | Classification | Effective Date | Review Date

2. VERSION CONTROL TABLE
   Columns: Version | Date | Author | Description of Change
   Start with: 1.0 | today's date | {author} | Initial release

3. CONFIDENTIALITY NOTICE
   One paragraph: formal proprietary IP protection statement appropriate for {document_type}

Document context:
  Industry: {industry}
  Department: {department}
  Document Type: {document_type}
  Author: {author}

Format professionally. Use markdown tables. No other content."""
)

# ─────────────────────────────────────────────────────────────────────────────
#  PER-SECTION PROMPT — called once for every section
# ─────────────────────────────────────────────────────────────────────────────
SECTION_PROMPT = PromptTemplate(
    input_variables=[
        "industry", "department", "document_type",
        "section_name", "section_freq",
        "q1_label", "q1_answer",
        "q2_label", "q2_answer",
        "previous_sections_summary",
    ],
    template="""You are an enterprise documentation specialist writing one section of a {document_type}.

DOCUMENT CONTEXT:
  Industry: {industry}
  Department: {department}
  Document Type: {document_type}

PREVIOUS SECTIONS (for context and continuity):
{previous_sections_summary}

YOUR TASK — Write ONLY this section:
  Section Name: {section_name}
  Frequency in enterprise docs: {section_freq}

USER-PROVIDED ANSWERS:
  Q: {q1_label}
  A: {q1_answer}

  Q: {q2_label}
  A: {q2_answer}

SECTION WRITING RULES:
1. Start with: ## {section_name}
2. Write 150–300 words for this section.
3. Expand the user's answers into professional enterprise prose. Do NOT repeat answers verbatim.
4. If this is "Roles and Responsibilities": format as RACI table (Responsible · Accountable · Consulted · Informed).
5. If this is "Exceptions and Limitations": include Force Majeure and Severability clauses where relevant.
6. If this is "Approvals and Sign-off": include a signature block table.
7. Maintain continuity with previous sections. Do not repeat content already covered.
8. Professional enterprise tone — formal, clear, authoritative.
9. Do NOT hallucinate — only expand from what the user provided.
10. Do NOT add section headers for other sections — write ONLY this one.

Write the {section_name} section now:"""
)

# ─────────────────────────────────────────────────────────────────────────────
#  ASSEMBLY PROMPT — final pass to ensure cohesion
# ─────────────────────────────────────────────────────────────────────────────
ASSEMBLY_PROMPT = PromptTemplate(
    input_variables=["document_type", "all_sections_text"],
    template="""You are an enterprise documentation specialist.

The following sections of a {document_type} have been generated independently.
Your task: perform a FINAL ASSEMBLY pass.

Rules:
1. Preserve ALL content from every section — do NOT remove or summarize anything.
2. Fix any inconsistencies in terminology between sections.
3. Ensure smooth transitions between sections.
4. Ensure consistent formatting (markdown headers, tables, bullet lists).
5. Do NOT add new content or sections not already present.
6. The document must read as a single unified professional enterprise document.

SECTIONS TO ASSEMBLE:
{all_sections_text}

Output the complete, final, assembled document:"""
)


def _get_model(temperature: float = 0.7, streaming: bool = False) -> ChatGroq:
    return ChatGroq(
        model="llama-3.3-70b-versatile",
        temperature=temperature,
        api_key=settings.GROQ_API_KEY,
        streaming=streaming,
    )


def _summarize_for_context(generated_sections: list[dict]) -> str:
    """
    Builds a brief summary of already-generated sections to give context
    to each subsequent section prompt. Prevents repetition, ensures continuity.
    """
    if not generated_sections:
        return "This is the first section — no previous sections exist yet."

    lines = ["Previously generated sections (brief summary for context):"]
    for sec in generated_sections:
        # Take first 200 chars of each section as context
        preview = sec["content"][:200].replace("\n", " ").strip()
        lines.append(f"  • {sec['name']}: {preview}…")
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
#  MAIN PUBLIC API
# ─────────────────────────────────────────────────────────────────────────────

async def generate_document_section_by_section(
    industry: str,
    department: str,
    doc_type: str,
    answers: dict,
    author: str = "Admin",
    doc_ref: str = "DOC-2026-001",
    do_final_assembly: bool = True,
) -> dict:
    """
    Generates a document section by section.
    Each section is a separate LLM call for better accuracy and formatting.

    Returns:
        {
            "content": str,          # full assembled document
            "sections": list[dict],  # individual section results
            "section_count": int,
            "word_count": int,
        }
    """
    sections = get_sections_for_doc_type(doc_type)
    model = _get_model(temperature=0.65)
    generated = []

    logger.info(f"Section-by-section generation: {doc_type} | {len(sections)} sections")

    # ── Step 1: Auto-generate header ─────────────────────────────────────────
    logger.info("Generating header (Metadata + Version Control + Confidentiality)")
    try:
        header_chain = HEADER_PROMPT | model | StrOutputParser()
        header_content = header_chain.invoke({
            "industry":      industry,
            "department":    department,
            "document_type": doc_type,
            "author":        author,
            "doc_ref":       doc_ref,
        })
        generated.append({
            "name":    "Administrative Header",
            "content": header_content,
            "auto":    True,
        })
        logger.info("Header generated ✓")
    except Exception as e:
        logger.error(f"Header generation failed: {e}")
        generated.append({
            "name":    "Administrative Header",
            "content": f"# {doc_type}\n\n*Document Metadata, Version Control, and Confidentiality Notice*",
            "auto":    True,
        })

    # ── Step 2: Generate each section independently ───────────────────────────
    section_chain = SECTION_PROMPT | model | StrOutputParser()

    for i, sec in enumerate(sections):
        section_name = sec["name"]
        section_freq = sec.get("freq", "stated")
        questions    = sec.get("questions", [])

        # Extract Q&A for this section (up to 2 questions)
        q1_label  = questions[0][1] if len(questions) > 0 else "Describe this section."
        q1_answer = answers.get(questions[0][0], "Not provided") if len(questions) > 0 else "Not provided"
        q2_label  = questions[1][1] if len(questions) > 1 else "Any additional details?"
        q2_answer = answers.get(questions[1][0], "Not provided") if len(questions) > 1 else "Not provided"

        # Build context from already-generated sections
        prev_summary = _summarize_for_context(
            [s for s in generated if not s.get("auto")]
        )

        logger.info(f"Generating section {i+1}/{len(sections)}: {section_name}")

        try:
            section_content = section_chain.invoke({
                "industry":                  industry,
                "department":                department,
                "document_type":             doc_type,
                "section_name":              section_name,
                "section_freq":              section_freq,
                "q1_label":                  q1_label,
                "q1_answer":                 q1_answer,
                "q2_label":                  q2_label,
                "q2_answer":                 q2_answer,
                "previous_sections_summary": prev_summary,
            })
            generated.append({
                "name":    section_name,
                "content": section_content,
                "auto":    False,
            })
            logger.info(f"Section '{section_name}' ✓ ({len(section_content.split())} words)")

        except Exception as e:
            logger.error(f"Section '{section_name}' failed: {e}")
            generated.append({
                "name":    section_name,
                "content": f"## {section_name}\n\n*Section generation encountered an error. Please review manually.*",
                "auto":    False,
            })

    # ── Step 3: Assemble all sections ─────────────────────────────────────────
    all_text = "\n\n".join(s["content"] for s in generated)

    if do_final_assembly and len(sections) > 3:
        logger.info("Running final assembly pass for cohesion…")
        try:
            assembly_chain  = ASSEMBLY_PROMPT | _get_model(temperature=0.3) | StrOutputParser()
            assembled       = assembly_chain.invoke({
                "document_type":   doc_type,
                "all_sections_text": all_text,
            })
            final_content = assembled
            logger.info("Assembly pass complete ✓")
        except Exception as e:
            logger.warning(f"Assembly pass failed (using raw join): {e}")
            final_content = all_text
    else:
        final_content = all_text

    word_count = len(final_content.split())
    logger.info(f"Document complete: {word_count} words across {len(generated)} sections")

    return {
        "content":       final_content,
        "sections":      generated,
        "section_count": len(sections),
        "word_count":    word_count,
    }


async def stream_document_section_by_section(
    industry: str,
    department: str,
    doc_type: str,
    answers: dict,
    author: str = "Admin",
    doc_ref: str = "DOC-2026-001",
) -> AsyncGenerator[dict, None]:
    """
    Streaming version — yields progress events as each section is generated.
    Used by the Streamlit UI for real-time progress display.

    Yields dicts:
        {"event": "start",    "section": str, "total": int, "index": int}
        {"event": "section",  "section": str, "content": str, "index": int}
        {"event": "header",   "content": str}
        {"event": "complete", "content": str, "word_count": int}
        {"event": "error",    "section": str, "error": str}
    """
    sections = get_sections_for_doc_type(doc_type)
    model    = _get_model(temperature=0.65)
    generated = []
    total = len(sections) + 1  # +1 for header

    # ── Header ────────────────────────────────────────────────────────────────
    yield {"event": "start", "section": "Administrative Header", "index": 0, "total": total}
    try:
        header_chain = HEADER_PROMPT | model | StrOutputParser()
        header_content = header_chain.invoke({
            "industry": industry, "department": department,
            "document_type": doc_type, "author": author, "doc_ref": doc_ref,
        })
        generated.append({"name": "Administrative Header", "content": header_content, "auto": True})
        yield {"event": "header", "content": header_content, "index": 0}
    except Exception as e:
        yield {"event": "error", "section": "Administrative Header", "error": str(e)}

    # ── Sections ──────────────────────────────────────────────────────────────
    section_chain = SECTION_PROMPT | model | StrOutputParser()

    for i, sec in enumerate(sections):
        section_name = sec["name"]
        section_freq = sec.get("freq", "stated")
        questions    = sec.get("questions", [])

        yield {"event": "start", "section": section_name, "index": i + 1, "total": total}

        q1_label  = questions[0][1] if len(questions) > 0 else "Describe this section."
        q1_answer = answers.get(questions[0][0], "Not provided") if len(questions) > 0 else "Not provided"
        q2_label  = questions[1][1] if len(questions) > 1 else "Additional details?"
        q2_answer = answers.get(questions[1][0], "Not provided") if len(questions) > 1 else "Not provided"

        prev_summary = _summarize_for_context([s for s in generated if not s.get("auto")])

        try:
            content = section_chain.invoke({
                "industry": industry, "department": department,
                "document_type": doc_type, "section_name": section_name,
                "section_freq": section_freq, "q1_label": q1_label,
                "q1_answer": q1_answer, "q2_label": q2_label,
                "q2_answer": q2_answer, "previous_sections_summary": prev_summary,
            })
            generated.append({"name": section_name, "content": content, "auto": False})
            yield {"event": "section", "section": section_name, "content": content, "index": i + 1}

        except Exception as e:
            yield {"event": "error", "section": section_name, "error": str(e)}

    # ── Final assembly ────────────────────────────────────────────────────────
    all_text = "\n\n".join(s["content"] for s in generated)
    word_count = len(all_text.split())
    yield {"event": "complete", "content": all_text, "word_count": word_count}
